spring:
  profiles:
    default: local
  datasource:
    url: jdbc:mysql://localhost:3306/recipe_sns
    username: root
    password: hp12081208
    driver-class-name: com.mysql.cj.jdbc.Driver

---
spring:
  config:
    activate:
      on-profile: local
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
logging:
  level:
    org.springframework.jdbc.core: DEBUG
    org.springframework.jdbc.support: DEBUG

---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:~/test;MODE=MYSQL;
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
  sql:
    init:
      mode: never

logging:
  level:
    org.hibernate.sql: debug
    org.hibernate.type: trace

---
spring:
  config:
    activate:
      on-profile: prod
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true