spring:
  profiles:
    default: local
  datasource:
    url: jdbc:mysql://localhost:3306/recipe_sns
    username: root
    password: hp12081208
    driver-class-name: com.mysql.cj.jdbc.Driver

---
spring:
  config:
    activate:
      on-profile: local
logging:
  level:
    org.springframework.jdbc.core: DEBUG
    org.springframework.jdbc.support: DEBUG

---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:~/test;MODE=MYSQL;
    username: sa
    password:
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql

logging:
  level:
    org.springframework.jdbc.core: DEBUG
    org.springframework.jdbc.support: DEBUG
